[2024-09-12T12:53:39.323-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T12:53:39.330-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.update_data manual__2024-09-12T15:53:36.948474+00:00 [queued]>
[2024-09-12T12:53:39.335-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.update_data manual__2024-09-12T15:53:36.948474+00:00 [queued]>
[2024-09-12T12:53:39.335-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-12T12:53:39.348-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): update_data> on 2024-09-12 15:53:36.948474+00:00
[2024-09-12T12:53:39.350-0300] {standard_task_runner.py:72} INFO - Started process 7183 to run task
[2024-09-12T12:53:39.352-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'update_data', 'manual__2024-09-12T15:53:36.948474+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpbbarmowk']
[2024-09-12T12:53:39.354-0300] {standard_task_runner.py:105} INFO - Job 34: Subtask update_data
[2024-09-12T12:53:39.376-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.update_data manual__2024-09-12T15:53:36.948474+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-12T12:53:39.425-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='update_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T15:53:36.948474+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T15:53:36.948474+00:00'
[2024-09-12T12:53:39.426-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T12:53:39.438-0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T12:53:39.440-0300] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-09-12T12:53:39.440-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/airflow/dags/dag_test.py", line 77, in update_spreadsheet_data
    spreadsheet = hook.batch_update_values('1EGfO6zUlbZqMfXmMU7_CXh4PpYpQTFgCjyVuqM1fT3I', "A:C", [["teste", "teste2"]["value 1", "value 2"]])
TypeError: list indices must be integers or slices, not tuple
[2024-09-12T12:53:39.444-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_test, task_id=update_data, run_id=manual__2024-09-12T15:53:36.948474+00:00, execution_date=20240912T155336, start_date=20240912T155339, end_date=20240912T155339
[2024-09-12T12:53:39.456-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T12:53:39.456-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 34 for task update_data (list indices must be integers or slices, not tuple; 7183)
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/airflow/dags/dag_test.py", line 77, in update_spreadsheet_data
    spreadsheet = hook.batch_update_values('1EGfO6zUlbZqMfXmMU7_CXh4PpYpQTFgCjyVuqM1fT3I', "A:C", [["teste", "teste2"]["value 1", "value 2"]])
TypeError: list indices must be integers or slices, not tuple
[2024-09-12T12:53:39.485-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-12T12:53:39.497-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T12:53:39.504-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
