[2024-09-12T04:00:37.430-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T04:00:37.437-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T07:00:35.338324+00:00 [queued]>
[2024-09-12T04:00:37.440-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T07:00:35.338324+00:00 [queued]>
[2024-09-12T04:00:37.440-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-12T04:00:37.451-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_data_from_gs> on 2024-09-12 07:00:35.338324+00:00
[2024-09-12T04:00:37.454-0300] {standard_task_runner.py:72} INFO - Started process 75204 to run task
[2024-09-12T04:00:37.457-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'get_data_from_gs', 'manual__2024-09-12T07:00:35.338324+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpcqlj48iu']
[2024-09-12T04:00:37.458-0300] {standard_task_runner.py:105} INFO - Job 26: Subtask get_data_from_gs
[2024-09-12T04:00:37.480-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.get_data_from_gs manual__2024-09-12T07:00:35.338324+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-12T04:00:37.531-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='get_data_from_gs' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T07:00:35.338324+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T07:00:35.338324+00:00'
[2024-09-12T04:00:37.531-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T04:00:37.544-0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T04:00:37.545-0300] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-09-12T04:00:38.394-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/airflow/dags/dag_test.py", line 68, in get_data_from_spreadsheet
    spreadsheet = hook.get_values('1EGfO6zUlbZqMfXmMU7_CXh4PpYpQTFgCjyVuqM1fT3I', "A1:*")
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/suite/hooks/sheets.py", line 106, in get_values
    service.spreadsheets()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1EGfO6zUlbZqMfXmMU7_CXh4PpYpQTFgCjyVuqM1fT3I/values/A1%3A%2A?majorDimension=DIMENSION_UNSPECIFIED&valueRenderOption=FORMATTED_VALUE&dateTimeRenderOption=SERIAL_NUMBER&alt=json returned "Unable to parse range: A1:*". Details: "Unable to parse range: A1:*">
[2024-09-12T04:00:38.397-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_test, task_id=get_data_from_gs, run_id=manual__2024-09-12T07:00:35.338324+00:00, execution_date=20240912T070035, start_date=20240912T070037, end_date=20240912T070038
[2024-09-12T04:00:38.429-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T04:00:38.429-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task get_data_from_gs (<HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1EGfO6zUlbZqMfXmMU7_CXh4PpYpQTFgCjyVuqM1fT3I/values/A1%3A%2A?majorDimension=DIMENSION_UNSPECIFIED&valueRenderOption=FORMATTED_VALUE&dateTimeRenderOption=SERIAL_NUMBER&alt=json returned "Unable to parse range: A1:*". Details: "Unable to parse range: A1:*">; 75204)
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/airflow/dags/dag_test.py", line 68, in get_data_from_spreadsheet
    spreadsheet = hook.get_values('1EGfO6zUlbZqMfXmMU7_CXh4PpYpQTFgCjyVuqM1fT3I', "A1:*")
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/suite/hooks/sheets.py", line 106, in get_values
    service.spreadsheets()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1EGfO6zUlbZqMfXmMU7_CXh4PpYpQTFgCjyVuqM1fT3I/values/A1%3A%2A?majorDimension=DIMENSION_UNSPECIFIED&valueRenderOption=FORMATTED_VALUE&dateTimeRenderOption=SERIAL_NUMBER&alt=json returned "Unable to parse range: A1:*". Details: "Unable to parse range: A1:*">
[2024-09-12T04:00:38.472-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-12T04:00:38.480-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T04:00:38.480-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
