[2024-09-16T17:49:53.939-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-16T17:49:53.949-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_mal_scrapy.scrape_data manual__2024-09-16T20:49:50.938833+00:00 [queued]>
[2024-09-16T17:49:53.953-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_mal_scrapy.scrape_data manual__2024-09-16T20:49:50.938833+00:00 [queued]>
[2024-09-16T17:49:53.953-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-16T17:49:53.967-0300] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): scrape_data> on 2024-09-16 20:49:50.938833+00:00
[2024-09-16T17:49:53.972-0300] {standard_task_runner.py:72} INFO - Started process 62954 to run task
[2024-09-16T17:49:53.975-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_mal_scrapy', 'scrape_data', 'manual__2024-09-16T20:49:50.938833+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/dag_mal_scrapy.py', '--cfg-path', '/tmp/tmpdvt2kyvw']
[2024-09-16T17:49:53.977-0300] {standard_task_runner.py:105} INFO - Job 87: Subtask scrape_data
[2024-09-16T17:49:54.008-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_mal_scrapy.scrape_data manual__2024-09-16T20:49:50.938833+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-16T17:49:54.073-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_mal_scrapy' AIRFLOW_CTX_TASK_ID='scrape_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T20:49:50.938833+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-16T20:49:50.938833+00:00'
[2024-09-16T17:49:54.074-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-16T17:49:54.087-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-16T17:49:54.089-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 ./python/mal_scrapy.py']
[2024-09-16T17:49:54.099-0300] {subprocess.py:86} INFO - Output:
[2024-09-16T17:49:54.115-0300] {subprocess.py:93} INFO - python3: can't open file '/tmp/airflowtmppk9lw51q/./python/mal_scrapy.py': [Errno 2] No such file or directory
[2024-09-16T17:49:54.118-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-16T17:49:54.126-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-16T17:49:54.128-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_mal_scrapy, task_id=scrape_data, run_id=manual__2024-09-16T20:49:50.938833+00:00, execution_date=20240916T204950, start_date=20240916T204953, end_date=20240916T204954
[2024-09-16T17:49:54.142-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-16T17:49:54.143-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 87 for task scrape_data (Bash command failed. The command returned a non-zero exit code 2.; 62954)
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-16T17:49:54.189-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-16T17:49:54.200-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-16T17:49:54.200-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
