[2024-09-16T16:04:23.601-0300] {processor.py:186} INFO - Started process (PID=4137) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:04:23.602-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:04:23.603-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:04:23.603-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:04:23.608-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:04:23.606-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:04:23.608-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:04:23.622-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.024 seconds
[2024-09-16T16:04:54.736-0300] {processor.py:186} INFO - Started process (PID=4487) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:04:54.737-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:04:54.739-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:04:54.738-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:04:54.742-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:04:54.741-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:04:54.742-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:04:54.754-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.021 seconds
[2024-09-16T16:05:14.869-0300] {processor.py:186} INFO - Started process (PID=4628) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:05:14.870-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:05:14.872-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:05:14.872-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:05:14.874-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:05:14.874-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 13, in <module>
    start_date=pendulum.datetime(2024, 16, 9, tz="UTC"),
  File "/home/gabzarp/.local/lib/python3.10/site-packages/pendulum/__init__.py", line 143, in datetime
    return DateTime.create(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/pendulum/datetime.py", line 105, in create
    dt = datetime.datetime(
ValueError: month must be in 1..12
[2024-09-16T16:05:14.875-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:05:14.889-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.025 seconds
[2024-09-16T16:05:45.072-0300] {processor.py:186} INFO - Started process (PID=5165) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:05:45.073-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:05:45.075-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:05:45.075-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:05:45.077-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:05:45.076-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 13, in <module>
    start_date=pendulum.datetime(2024, 16, 9, tz="UTC"),
  File "/home/gabzarp/.local/lib/python3.10/site-packages/pendulum/__init__.py", line 143, in datetime
    return DateTime.create(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/pendulum/datetime.py", line 105, in create
    dt = datetime.datetime(
ValueError: month must be in 1..12
[2024-09-16T16:05:45.077-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:05:45.090-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.022 seconds
[2024-09-16T16:06:00.174-0300] {processor.py:186} INFO - Started process (PID=5522) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:06:00.174-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:06:00.176-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:06:00.175-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:06:00.181-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:06:00.180-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:06:00.182-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:06:00.195-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.025 seconds
[2024-09-16T16:06:30.380-0300] {processor.py:186} INFO - Started process (PID=6136) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:06:30.381-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:06:30.382-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:06:30.382-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:06:30.385-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:06:30.384-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:06:30.385-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:06:30.398-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.022 seconds
[2024-09-16T16:07:00.581-0300] {processor.py:186} INFO - Started process (PID=6582) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:07:00.582-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:07:00.583-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:07:00.583-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:07:00.586-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:07:00.586-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:07:00.587-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:07:00.598-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.021 seconds
[2024-09-16T16:07:30.784-0300] {processor.py:186} INFO - Started process (PID=6977) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:07:30.785-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:07:30.786-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:07:30.786-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:07:30.789-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:07:30.789-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:07:30.790-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:07:30.803-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.022 seconds
[2024-09-16T16:08:00.984-0300] {processor.py:186} INFO - Started process (PID=7190) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:08:00.985-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:08:00.986-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:08:00.986-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:08:00.989-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:08:00.988-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:08:00.989-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:08:01.002-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.022 seconds
[2024-09-16T16:08:31.200-0300] {processor.py:186} INFO - Started process (PID=7585) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:08:31.200-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:08:31.201-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:08:31.201-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:08:31.205-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:08:31.204-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:08:31.205-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:08:31.217-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.021 seconds
[2024-09-16T16:09:01.401-0300] {processor.py:186} INFO - Started process (PID=7798) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:09:01.402-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:09:01.403-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:09:01.403-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:09:01.406-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:09:01.406-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:09:01.407-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:09:01.419-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.022 seconds
[2024-09-16T16:09:31.719-0300] {processor.py:186} INFO - Started process (PID=8250) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:09:31.721-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:09:31.722-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:09:31.722-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:09:31.725-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:09:31.724-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:09:31.725-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:09:31.872-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.156 seconds
[2024-09-16T16:10:02.945-0300] {processor.py:186} INFO - Started process (PID=8511) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:10:02.946-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:10:02.947-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:10:02.947-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:10:02.951-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:10:02.950-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:10:02.951-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:10:02.965-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.024 seconds
[2024-09-16T16:10:33.864-0300] {processor.py:186} INFO - Started process (PID=8893) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:10:33.865-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:10:33.866-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:10:33.866-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:10:33.869-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:10:33.869-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:10:33.870-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:10:33.883-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.023 seconds
[2024-09-16T16:11:04.580-0300] {processor.py:186} INFO - Started process (PID=9169) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:11:04.581-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:11:04.583-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:11:04.582-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:11:04.586-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:11:04.585-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:11:04.586-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:11:04.599-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.022 seconds
[2024-09-16T16:11:34.767-0300] {processor.py:186} INFO - Started process (PID=9501) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:11:34.768-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:11:34.769-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:11:34.769-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:11:34.772-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:11:34.771-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:11:34.772-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:11:34.785-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.023 seconds
[2024-09-16T16:12:04.946-0300] {processor.py:186} INFO - Started process (PID=9770) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:12:04.947-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:12:04.949-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:12:04.949-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:12:04.952-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:12:04.951-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:12:04.952-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:12:05.075-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.133 seconds
[2024-09-16T16:12:35.232-0300] {processor.py:186} INFO - Started process (PID=10102) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:12:35.233-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:12:35.234-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:12:35.234-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:12:35.237-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:12:35.236-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:12:35.237-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:12:35.250-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.022 seconds
[2024-09-16T16:13:05.421-0300] {processor.py:186} INFO - Started process (PID=10376) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:13:05.422-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:13:05.424-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:13:05.424-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:13:05.427-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:13:05.426-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:13:05.427-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:13:05.441-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.023 seconds
[2024-09-16T16:13:35.608-0300] {processor.py:186} INFO - Started process (PID=10707) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:13:35.609-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:13:35.610-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:13:35.610-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:13:35.614-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:13:35.613-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:13:35.614-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:13:35.626-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.021 seconds
[2024-09-16T16:14:05.794-0300] {processor.py:186} INFO - Started process (PID=10976) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:14:05.795-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:14:05.797-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:14:05.797-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:14:05.800-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:14:05.800-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:14:05.801-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:14:05.923-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.133 seconds
[2024-09-16T16:14:37.205-0300] {processor.py:186} INFO - Started process (PID=11379) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:14:37.206-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:14:37.208-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:14:37.207-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:14:37.211-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:14:37.210-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:14:37.211-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:14:37.222-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.020 seconds
[2024-09-16T16:15:07.629-0300] {processor.py:186} INFO - Started process (PID=11679) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:07.631-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:15:07.632-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:15:07.632-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:07.635-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:15:07.634-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = PythonOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2024-09-16T16:15:07.635-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:07.649-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.023 seconds
[2024-09-16T16:15:10.923-0300] {processor.py:186} INFO - Started process (PID=11734) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:10.924-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:15:10.925-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:15:10.925-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:10.928-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:15:10.927-0300] {dagbag.py:386} ERROR - Failed to import: /home/gabzarp/airflow/dags/dag_mal_scrappy.py
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gabzarp/airflow/dags/dag_mal_scrappy.py", line 17, in <module>
    scrape_data = BashOperator(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2024-09-16T16:15:10.928-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:11.049-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.131 seconds
[2024-09-16T16:15:20.875-0300] {processor.py:186} INFO - Started process (PID=11833) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:20.875-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:15:20.877-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:15:20.877-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:20.883-0300] {processor.py:925} INFO - DAG(s) 'dag_test' retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:20.945-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:15:20.945-0300] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-16T16:15:21.053-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:15:21.053-0300] {dag.py:4156} INFO - Setting next_dagrun for dag_test to None, run_after=None
[2024-09-16T16:15:21.073-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.202 seconds
[2024-09-16T16:15:34.249-0300] {processor.py:186} INFO - Started process (PID=12018) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:34.249-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:15:34.251-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:15:34.251-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:34.258-0300] {processor.py:925} INFO - DAG(s) 'dag_test' retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:15:34.263-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:15:34.263-0300] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-16T16:15:34.272-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:15:34.272-0300] {dag.py:4156} INFO - Setting next_dagrun for dag_test to None, run_after=None
[2024-09-16T16:15:34.387-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.142 seconds
[2024-09-16T16:16:04.564-0300] {processor.py:186} INFO - Started process (PID=12313) to work on /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:16:04.566-0300] {processor.py:914} INFO - Processing file /home/gabzarp/airflow/dags/dag_mal_scrappy.py for tasks to queue
[2024-09-16T16:16:04.569-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:16:04.569-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:16:04.577-0300] {processor.py:925} INFO - DAG(s) 'dag_test' retrieved from /home/gabzarp/airflow/dags/dag_mal_scrappy.py
[2024-09-16T16:16:04.590-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:16:04.590-0300] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-16T16:16:04.603-0300] {logging_mixin.py:190} INFO - [2024-09-16T16:16:04.603-0300] {dag.py:4156} INFO - Setting next_dagrun for dag_test to None, run_after=None
[2024-09-16T16:16:04.622-0300] {processor.py:208} INFO - Processing /home/gabzarp/airflow/dags/dag_mal_scrappy.py took 0.062 seconds
