[2024-09-12T03:01:00.331-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T03:01:00.336-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.create_spreadsheet manual__2024-09-12T06:00:57.398904+00:00 [queued]>
[2024-09-12T03:01:00.341-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.create_spreadsheet manual__2024-09-12T06:00:57.398904+00:00 [queued]>
[2024-09-12T03:01:00.341-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-12T03:01:00.353-0300] {taskinstance.py:2888} INFO - Executing <Task(GoogleSheetsCreateSpreadsheetOperator): create_spreadsheet> on 2024-09-12 06:00:57.398904+00:00
[2024-09-12T03:01:00.355-0300] {standard_task_runner.py:72} INFO - Started process 41300 to run task
[2024-09-12T03:01:00.357-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'create_spreadsheet', 'manual__2024-09-12T06:00:57.398904+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpjs_cxacz']
[2024-09-12T03:01:00.359-0300] {standard_task_runner.py:105} INFO - Job 16: Subtask create_spreadsheet
[2024-09-12T03:01:00.392-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.create_spreadsheet manual__2024-09-12T06:00:57.398904+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-12T03:01:00.439-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='create_spreadsheet' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T06:00:57.398904+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T06:00:57.398904+00:00'
[2024-09-12T03:01:00.439-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T03:01:00.451-0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T03:01:00.452-0300] {base.py:84} INFO - Retrieving connection 'connection_dag_test_None'
[2024-09-12T03:01:00.452-0300] {sheets.py:411} INFO - Creating spreadsheet: Test1
[2024-09-12T03:01:00.456-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 306, in get_credentials_and_project_id
    keyfile_dict_json = json.loads(keyfile_dict)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/suite/operators/sheets.py", line 75, in execute
    spreadsheet = hook.create_spreadsheet(spreadsheet=self.spreadsheet)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/suite/hooks/sheets.py", line 414, in create_spreadsheet
    self.get_conn().spreadsheets().create(body=spreadsheet).execute(num_retries=self.num_retries)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/suite/hooks/sheets.py", line 75, in get_conn
    http_authorized = self._authorize()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 405, in _authorize
    credentials = self.get_credentials()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 363, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials_and_project_id
    raise AirflowException("Invalid key JSON.")
airflow.exceptions.AirflowException: Invalid key JSON.
[2024-09-12T03:01:00.458-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_test, task_id=create_spreadsheet, run_id=manual__2024-09-12T06:00:57.398904+00:00, execution_date=20240912T060057, start_date=20240912T060100, end_date=20240912T060100
[2024-09-12T03:01:00.467-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T03:01:00.467-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task create_spreadsheet (Invalid key JSON.; 41300)
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 306, in get_credentials_and_project_id
    keyfile_dict_json = json.loads(keyfile_dict)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/suite/operators/sheets.py", line 75, in execute
    spreadsheet = hook.create_spreadsheet(spreadsheet=self.spreadsheet)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/suite/hooks/sheets.py", line 414, in create_spreadsheet
    self.get_conn().spreadsheets().create(body=spreadsheet).execute(num_retries=self.num_retries)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/suite/hooks/sheets.py", line 75, in get_conn
    http_authorized = self._authorize()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 405, in _authorize
    credentials = self.get_credentials()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 363, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials_and_project_id
    raise AirflowException("Invalid key JSON.")
airflow.exceptions.AirflowException: Invalid key JSON.
[2024-09-12T03:01:00.490-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-12T03:01:00.498-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T03:01:00.498-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
