[2024-09-12T13:18:49.814-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T13:18:49.820-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_test.update_data manual__2024-09-12T16:18:44.633396+00:00 [queued]>
[2024-09-12T13:18:49.824-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_test.update_data manual__2024-09-12T16:18:44.633396+00:00 [queued]>
[2024-09-12T13:18:49.824-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-12T13:18:49.837-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): update_data> on 2024-09-12 16:18:44.633396+00:00
[2024-09-12T13:18:49.839-0300] {standard_task_runner.py:72} INFO - Started process 22151 to run task
[2024-09-12T13:18:49.841-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_test', 'update_data', 'manual__2024-09-12T16:18:44.633396+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag_test.py', '--cfg-path', '/tmp/tmpcbg6ne4o']
[2024-09-12T13:18:49.843-0300] {standard_task_runner.py:105} INFO - Job 52: Subtask update_data
[2024-09-12T13:18:49.867-0300] {task_command.py:467} INFO - Running <TaskInstance: dag_test.update_data manual__2024-09-12T16:18:44.633396+00:00 [running]> on host DESKTOP-PEJJLJO.
[2024-09-12T13:18:49.912-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_test' AIRFLOW_CTX_TASK_ID='update_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T16:18:44.633396+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T16:18:44.633396+00:00'
[2024-09-12T13:18:49.913-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T13:18:49.925-0300] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T13:18:49.927-0300] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2024-09-12T13:18:49.927-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/airflow/dags/dag_test.py", line 76, in update_spreadsheet_data
    data = taskinstance.xcom_pull('get_data_from_gs', 'dag_test', 'return_value')
AttributeError: module 'airflow.models.taskinstance' has no attribute 'xcom_pull'
[2024-09-12T13:18:49.930-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_test, task_id=update_data, run_id=manual__2024-09-12T16:18:44.633396+00:00, execution_date=20240912T161844, start_date=20240912T161849, end_date=20240912T161849
[2024-09-12T13:18:49.940-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T13:18:49.940-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 52 for task update_data (module 'airflow.models.taskinstance' has no attribute 'xcom_pull'; 22151)
Traceback (most recent call last):
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/gabzarp/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/gabzarp/airflow/dags/dag_test.py", line 76, in update_spreadsheet_data
    data = taskinstance.xcom_pull('get_data_from_gs', 'dag_test', 'return_value')
AttributeError: module 'airflow.models.taskinstance' has no attribute 'xcom_pull'
[2024-09-12T13:18:49.974-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-12T13:18:49.982-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T13:18:49.983-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
